### ISSUE TITLE
Weather icon

### ISSUE THREAD

**Issue by vizaie** [GiovanniCardamone/ConkyMaterial#1] opened 2021-10-02 15:52 UTC
It doesn't show weather icon and temp. 

time.lua tried to access data.current.weather[1].icon 
But I think it should be 
data.current.weather[0].icon

weather icon won't appear even after doing above change

And change the link in READ.ME from accweather to openweather.

**Comment by GiovanniCardamone** [comment] 2021-10-02 17:22
Lua Array index start at 1, you need a weather key to extract info, did you get one and added to your ENV variables?

**Comment by vizaie** [comment] 2021-10-03 06:24
Yes, I have added the ENV variable 

I am getting the json when I paste the url in the browser and weather.json looks fine.

![Screenshot_20211003_115251](https://user-images.githubusercontent.com/58224705/135742631-48850188-451c-4f23-a983-5782b5dfc652.png)

weather.json content :

{"lat":16.4805,"lon":79.4385,"timezone":"Asia/Kolkata","timezone_offset":19800,"current":{"dt":1633241666,"sunrise":1633221146,"sunset":1633264200,"temp":31.79,"feels_like":35.47,"pressure":1009,"humidity":56,"dew_point":21.93,"uvi":10.63,"clouds":52,"visibility":10000,"wind_speed":2.29,"wind_deg":94,"wind_gust":2.73,"weather":[{"id":803,"main":"Clouds","description":"nubi sparse","icon":"04d"}]}}

**Comment by GiovanniCardamone** [comment] 2021-10-03 08:16
did you have `jq` installed?

**Comment by GiovanniCardamone** [comment] 2021-10-03 08:16
this one: https://stedolan.github.io/jq/

**Comment by GiovanniCardamone** [comment] 2021-10-03 08:17
sorry i wrote the REAME in a rush xD so maybe i have to provide better installation steps :P sorry about that, anyway command is in the requirements

**Comment by GiovanniCardamone** [comment] 2021-10-03 08:18
also i think you need to install my font or as you can see the box are not well stretched, the font name is "GT America"

**Comment by GiovanniCardamone** [comment] 2021-10-03 08:19
![Screenshot_03_10_2021-10_19_00](https://user-images.githubusercontent.com/5117748/135745746-056513e5-78e5-4c7f-ae26-6588a2ec31aa.png)

**Comment by GiovanniCardamone** [comment] 2021-10-03 08:20
![Screenshot_03_10_2021-10_19_57](https://user-images.githubusercontent.com/5117748/135745768-ac7d645a-432a-4982-9b42-d99d1777cd6a.png)

**Comment by vizaie** [comment] 2021-10-03 12:26
executing only time_rc gives me erros.
I did 
`conky -c time_rc`

output is 
`conky: llua_do_call: function conky_main execution failed: .///_json.lua:186: invalid number '16,4805' at line 1 col 8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    13  100    13    0     0     10      0  0:00:01  0:00:01 --:--:--    10
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   361  100   361    0     0   2398      0 --:--:-- --:--:-- --:--:--  2406
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   400  100   400    0     0   1285      0 --:--:-- --:--:-- --:--:--  1286
conky: llua_do_call: function conky_format_weather execution failed: .///_json.lua:186: invalid number '16,4805' at line 1 col 8
conky: llua_do_call: function conky_main execution failed: .///_json.lua:186: invalid number '16,4805' at line 1 col 8
conky: llua_do_call: function conky_main execution failed: .///_json.lua:186: invalid number '16,4805' at line 1 col 8
conky: llua_do_call: function conky_format_weather execution failed: .///_json.lua:186: invalid number '16,4805' at line 1 col 8
conky: llua_do_call: function conky_main execution failed: .///_json.lua:186: invalid number '16,4805' at line 1 col 8
^C
`
I think there is something wrong with _json.lua. Do I have to install something related to json?

**Comment by GiovanniCardamone** [comment] 2021-10-03 12:59
yeah i think i know what the problem is, is something related to the fact that my system use `,` (comma) for decimal notations, and yours uses `.` (dot)

i can suggest an easy fix for you than i will  had something to handle both cases:

in `_json.lua`

replace those rows:

| row number | original instruction | to replace instruction |
| --- | --- | --- |
| 209 | `local n2 = tonumber( s:gsub("%.", ","):sub(7, 10), 16 )` | `local n2 = tonumber( s:gsub("%.", "."):sub(7, 10), 16 )` |
| 262 | `local s = str:gsub("%.", ","):sub(i, x - 1)` | `local s = str:gsub("%.", "."):sub(i, x - 1)` |

let me know if that helps you:

p.s.

GPU name and CPU name are hardcoded because original names from the manufacturer are too long. just put yours in

cpu_rc
gpu_rc

**Comment by vizaie** [comment] 2021-10-03 13:17
Yes, I did it

It thought the problem could be in _json and grabbed another json parser **dkjson** and placed it in the folder

changed the line 
`json = require "./_json"`
to 
`json = require "./dkjson"`

![Screenshot_20211003_184606](https://user-images.githubusercontent.com/58224705/135755319-500df63a-c6cc-432e-b00f-7d5d81efe188.png)

**Comment by vizaie** [comment] 2021-10-03 13:22
About the CPU and GPU

My CPU is similar to yours but GPU is different I will change it.
You also hardcoded the wifi card which won't show anything in NET for others I changed it already according to my card.

**Comment by GiovanniCardamone** [comment] 2021-10-03 13:31
Nice! I gonna close this issue.

Thanks for spotting that bug for me.

P.s. remember to leave a star if you like the project :)

**Closed as completed by GiovanniCardamone** 2021-10-03 13:31 UTC
Labels: bug, help wanted
